### ISSUE TITLE
Linux and MAC script

### ISSUE THREAD

**Issue by toniall** [securityjoes/Crowdstrike-Deploy#1]
#!/bin/bash

# Crowdstrike-Deploy Banner
echo ""
echo "  ██████╗██████╗  ██████╗ ██╗    ██╗██████╗ ███████╗████████╗██████╗ ██╗██╗  ██╗███████╗"
echo " ██╔════╝██╔══██╗██╔═══██╗██║    ██║██╔══██╗██╔════╝╚══██╔══╝██╔══██╗██║██║ ██╔╝██╔════╝"
echo " ██║     ██████╔╝██║   ██║██║ █╗ ██║██║  ██║███████╗   ██║   ██████╔╝██║█████╔╝ █████╗"
echo " ██║     ██╔══██╗██║   ██║██║███╗██║██║  ██║╚════██║   ██║   ██╔══██╗██║██╔═██╗ ██╔══╝"
echo " ╚██████╗██║  ██║╚██████╔╝╚███╔███╔╝██████╔╝███████║   ██║   ██║  ██║██║██║  ██╗███████╗"
echo "  ╚═════╝╚═╝  ╚═╝ ╚═════╝  ╚══╝╚══╝ ╚═════╝ ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝╚═╝  ╚══════╝"
echo ""
echo "                     ██████╗ ███████╗██████╗ ██╗      ██████╗ ██╗   ██╗"
echo "                     ██╔══██╗██╔════╝██╔══██╗██║     ██╔═══██╗╚██╗ ██╔╝"
echo "                     ██║  ██║█████╗  ██████╔╝██║     ██║   ██║ ╚████╔╝"
echo "                     ██║  ██║██╔══╝  ██╔═══╝ ██║     ██║   ██║  ╚██╔╝"
echo "                     ██████╔╝███████╗██║     ███████╗╚██████╔╝   ██║"
echo "                     ╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝    ╚═╝"
echo ""
echo "                           Created & Maintained by: Eilay Yosfan"
echo "                                   GitHub.com/YosfanEilay"
echo "                                        Version: 1.0"
echo ""

###### Please Paste Your Information in Here ######
SensorLink="" # Crowdstrike Sensor Download Link
SensorSig1="" # Crowdstrike Sensor Hash (SHA256)
TenantCID=""  # Crowdstrike Tenant CID
TenantName="" # Crowdstrike Tenant Name
###################################################

# Prerequisite Variable Load
Hostname=$(hostname)
RunPath=$(pwd)
DstPath="$RunPath/CrowdstrikeSensor"

# Test if Host is Connected to the internet
if ping -c 2 8.8.8.8 &> /dev/null
then
    echo "[+] Host is connected to the internet."
else
    echo "[!] Host is not connected to the internet."
    exit
fi

# Test Connection to OneDrive
if ping -c 2 "onedrive.live.com" &> /dev/null
then
    echo "[+] OneDrive is reachable."
else
    echo "[!] OneDrive is not reachable, might be related to host network or organization policy. Deploy might fail."
fi

# Download Crowdstrike Sensor
echo "[+] Download has started. The time required will depend on the host's bandwidth."
curl -o $DstPath $SensorLink

# Check if the Downloaded Sensor File is Corrupted
SensorSig2=$(sha256sum $DstPath | awk '{ print $1 }')
if [ "$SensorSig1" == "$SensorSig2" ]; then
    echo "[+] Crowdstrike sensor was successfully downloaded. Sensor installation started."
else
    echo "[!] The sensor file is corrupted, likely due to an interrupted download. you can try again."
    rm -f $DstPath
    exit
fi

# Start Crowdstrike Installation Process
chmod +x $DstPath
$DstPath /install /quiet CID=$TenantCID
sleep 60

# Print Success Message
echo "[+] Done. $Hostname will be available on host management under the tenant $TenantName in 5-10 minutes."
echo ""

**Comment by YosfanEilay** [comment]
Hi @toniall 
Thanks for this enhancement, when I will want to add Linux\Mac support I will use this, thanks !
